# Generated by Django 2.2.2 on 2021-02-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210210_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth_date',
            new_name='birthDate',
        ),
    ]
