# Generated by Django 2.2.2 on 2021-02-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210210_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='appointment_start_time',
            new_name='startTime',
        ),
    ]
